#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and displays this data.

# Requirements:

# The exact format must be:
# OCCURENCE_NUMBER IP HTTP_CODE
# In list format
# Ordered from the greatest to the lowest number of occurrences

log_file="apache-access.log"

awk '{print $1, $9}' "$log_file" | sort | uniq -c | sort -r
