#!/usr/bin/env bash
# prints best school 10 times using while and on the 9th iteration, displays "Hi" on a new line

i=1
while [ $i -le 10 ]; do
  if [ $i -eq 9 ]; then
    echo "Hi"
  else
    echo "Best School"
  fi
  ((i++))
done
